name: ed_logic_handler
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/endmr11/ed_logic_handler

environment:
  sdk: '>=2.18.2 <3.0.0'
  

dependencies:
  async: ^2.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
